### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by gregoryduckworth** [nearform/testing-playground#14]
Scenario to be able to check/uncheck, similar to Radio Buttons.

**Comment by e-taniguti** [comment]
Let me know if these are the expected scenarios:
<img width="1269" alt="Screenshot 2023-10-27 at 18 25 08" src="https://github.com/nearform/testing-playground/assets/110396367/80b67dfa-8743-4469-933c-85b48f189be7">

<img width="1267" alt="Screenshot 2023-10-27 at 18 24 57" src="https://github.com/nearform/testing-playground/assets/110396367/819c3304-70ad-4fbc-bef2-36fffa77f7e4">

**Comment by e-taniguti** [comment]
PR adding the checkbox scenario:
https://github.com/nearform/testing-playground/pull/31
